### ISSUE TITLE
切换到重力播放的时候，手机后背向前方，视频应该要方向是前方。结果是地面

### ISSUE THREAD

**Issue by bulolo** [hanton/HTY360Player#1]
切换到重力播放的时候，手机后背向前方，视频应该要方向是前方。结果是地面

**Comment by bulolo** [comment]
具体表现为：当手机平放在桌面。然后切换模式为“跟随手机”模式的时候，把手机拿起背对前方，这时候看到的是正前方。但当手机原本是背面对着前方进行切换到“跟随手机”时候，切换完，就莫名奇妙的看的是地面了。

**Comment by mrliuning** [comment]
能调成无论手机如何放置，怎么看，都没有偏移吗？都是看到的是正前方的景象吗？如何调呢？

**Comment by bulolo** [comment]
当手机后背朝前时，在“跟随手机”模式下进行切换成手动，在手机后背朝前的情况看到的是地面，正常情况不应该是 朝着前面。当是手动的时候，手机后背朝前，切换自动，结果看到的是地下。
现在发现的问题是切换过程中会错乱掉，方向会出现错误。
这是我研究过的别的开源可以参考：https://github.com/kalfie/Virtual-Reality-Video---iOS
我是研究了这个的体验，然后同时看到您的开源，发现的两个不同体验的地方。

**Comment by mrliuning** [comment]
非常感谢您的回复，可以把开源HTY360Player修复好吗？

**Comment by Rannie** [comment]
原因出在参考的那个Attitude为第一次update时获取的CMAttitude 如果获取的时候不是水平冲下的话 以后每次根据欧拉角调整都会有问题。

**Comment by xiange123** [comment]
有没有最新修改过的demo啊？速度传上来啊

**Comment by mrliuning** [comment]
能做成和Jaunt VR一样的吗？根据手机转动来选择看哪个视频，或者选择前进后退

**Comment by hanton** [comment]
可能是demo的问题，已上传新的demo，请再试试

**Comment by hanton** [comment]
Same as https://github.com/hanton/HTY360Player/issues/11
