### ISSUE TITLE
一直push和pop ar播放页面，memory和CPU一直不释放，持续增加，怎么回事？

### ISSUE THREAD

**Issue by rockzengli** [hanton/HTY360Player#2]
一直点playDemo，播放下，再返回，在点playDemo，多次操作几次，memory和CPU一直累加，会导致app crash掉

**Comment by heshanghuixitou123** [comment]
请问你解决这个问题了吗

**Comment by Rannie** [comment]
这个 Demo 有一些内存问题 例如 malloc 却不 free

**Comment by heshanghuixitou123** [comment]
那你有没有修复过内存问题的demo啊

**Comment by iOHS** [comment]
please, clear issue

**Comment by hanton** [comment]
内存问题已在https://github.com/hanton/HTY360Player/commit/6f7373f234718049f4ffc6faa87c047420b06994 中fixed，请再试试
