### ISSUE TITLE
集成到自己的工程里有BUG怎么解决?

### ISSUE THREAD

**Issue by heshanghuixitou123** [hanton/HTY360Player#4]
集成到自己工程之后, 第一次运行就是黑屏, 之后随机有可能会黑屏, 这是什么原因导致的呢?

**Comment by heshanghuixitou123** [comment]
每次运行第一次进都是黑屏, 返回再进就没事了....

**Comment by SanPanG-K** [comment]
每次运行第一次进都是黑屏, 返回再进就没事了....  为什么 进去之后 显示的 是地面

**Comment by heshanghuixitou123** [comment]
请问黑屏问题解决了吗

**Comment by SanPanG-K** [comment]
没有解决，使用别的 代替了

**Comment by heshanghuixitou123** [comment]
使用别的库了吗? 用的什么库啊

**Comment by SanPanG-K** [comment]
http://www.utovr.com/sdk/download    这个有版权标示，看项目需求所需吧。

**Comment by YaTings** [comment]
有没有那种没有版权标识，没有广告的

**Comment by SanPanG-K** [comment]
这个没有广告吧...因为项目需求改变（图片展示，不用视频），所以没有继续深究。

**Comment by YaTings** [comment]
有utoVR-SDK的标识啊。

**Comment by heshanghuixitou123** [comment]
UtoVR免费版的有他的标识, 去不掉啊

**Comment by YaTings** [comment]
UtoVR不够灵活。我自己写了一个播放器，差不多可以实现基本的效果

**Comment by heshanghuixitou123** [comment]
可以发给我吗, 加我Q297087407吧

**Comment by hanton** [comment]
可能是demo的问题，已上传新的demo，代码也刚重构了，请再试试
