### ISSUE TITLE
Portrait support

### ISSUE THREAD

**Issue by fruitcoder** [hanton/HTY360Player#5]
This is really an amazing library and I thought about using it to mimic Facebooks NewsFeed with 360 videos playing automatically in a scroll view. But I couldn't get it to work in Portrait since the translations of pan and gyroscope just didn't translate well to the camera movement. Do you have any hints? Do do I have to rotate the matrix?

**Comment by tibewww** [comment]
Hi fruitcoder,

I have the same issue in Portrait, when moving the video is like being push to go back to a position, did you manage to fix this ?

Thanks :)

**Comment by hanton** [comment]
Hi @fruitcoder and @tibewww , sorry for the late reply, Portrait mode is supported now, please check out the latest code.
