### ISSUE TITLE
Memory warning before crash

### ISSUE THREAD

**Issue by marcoiacobelli** [hanton/HTY360Player#9]
Hi, great work! It's ok but some seconds after video starts, app crash with memory wornings! 

Log:
HTY360Player[1802:660394] Received memory warning.
Message from debugger: Terminated due to memory issue

**Comment by hanton** [comment]
hi @marcoiacobelli the bug is fixed at https://github.com/hanton/HTY360Player/commit/6f7373f234718049f4ffc6faa87c047420b06994
please have a try again
